
name: Process Borror Issue

on: 
  issues: 
    - opened
    - edited
    - deleted
    - transferred
    - pinned
    - unpinned
    - closed
    - reopened
    - assigned
    - unassigned
    - labeled
    - unlabeled
    - locked
    - unlocked
    - milestoned
    - demilestoned

jobs:
  logger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      - name: View log
        run: cat $GITHUB_EVENT_PATH
      

